services:
  remotex-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remotex-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: always
